// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujOGzWFwoRpD9Fi0HNrZ02wv5yNFDBGw',
    appId: '1:1032301852748:web:3bb7f000febbdba3c6dce9',
    messagingSenderId: '1032301852748',
    projectId: 'optair-connect',
    authDomain: 'optair-connect.firebaseapp.com',
    databaseURL: 'https://optair-connect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'optair-connect.appspot.com',
    measurementId: 'G-8F9Y1RXQ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTzeOWMXCecVmXdiWw4SW_-O7AtgfhsHY',
    appId: '1:1032301852748:android:6f48d075298c9c59c6dce9',
    messagingSenderId: '1032301852748',
    projectId: 'optair-connect',
    databaseURL: 'https://optair-connect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'optair-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVBIMOmZKcctbR1lyIM-rfNrOxU0RPKaw',
    appId: '1:1032301852748:ios:2f9a0f349965e5c3c6dce9',
    messagingSenderId: '1032301852748',
    projectId: 'optair-connect',
    databaseURL: 'https://optair-connect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'optair-connect.appspot.com',
    iosClientId: '1032301852748-0mfgo8knjd6ufv8t9lriicbm87uhk77a.apps.googleusercontent.com',
    iosBundleId: 'com.example.optairconnect',
  );
}
